# Generated by Django 2.2.5 on 2019-09-23 10:22

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Category Id')),
                ('category_name', models.CharField(max_length=200, verbose_name='Category Name')),
                ('category_description', models.CharField(max_length=200, verbose_name='Category Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
                'ordering': ['category_id'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Shop Id')),
                ('shop_name', models.CharField(max_length=200, verbose_name='Shop Name')),
                ('shop_owner', models.CharField(max_length=200, verbose_name='Shop owner')),
                ('shop_address', models.CharField(max_length=200, verbose_name='Shop Address')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shop',
                'ordering': ['shop_id'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Brand Id')),
                ('brand_name', models.CharField(max_length=200, verbose_name='Brand Name')),
                ('brand_description', models.CharField(max_length=200, verbose_name='Brand Description')),
                ('brand_p_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=22)),
                ('brand_q_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=22)),
                ('brand_n_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=22)),
                ('brand_d_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=22)),
                ('brand_l_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=22)),
                ('brand_xg_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=22)),
                ('brand_y_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=22)),
                ('brand_p_sale', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=22)),
                ('brand_q_sale', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=22)),
                ('brand_n_sale', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=22)),
                ('brand_d_sale', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=22)),
                ('brand_l_sale', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=22)),
                ('brand_xg_sale', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=22)),
                ('brand_y_sale', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=22)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.Category')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brand',
                'ordering': ['brand_id'],
            },
        ),
    ]
