# Generated by Django 2.2.5 on 2019-09-23 13:50

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_transaction_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Invoice Id')),
                ('invoice_brand_size', models.CharField(max_length=5, verbose_name='Brand Size')),
                ('invoice_brand_qty', models.IntegerField(verbose_name='Brand Quantity')),
                ('invoice_rate_per_case', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=22)),
                ('invoice_no_of_bottles', models.IntegerField(verbose_name='Number of Bottles')),
                ('invoice_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=22)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.Brand')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoice',
                'ordering': ['invoice_transaction_id'],
            },
        ),
    ]
