# Generated by Django 2.2.5 on 2019-09-26 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0002_invoice_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.Category'),
        ),
    ]
