# Generated by Django 2.2.5 on 2019-09-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0002_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('quantity_name', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Quantity Name')),
                ('quantity_bottles', models.IntegerField(verbose_name='Quantity bottles')),
            ],
            options={
                'verbose_name': 'Quantity',
                'verbose_name_plural': 'Quantities',
                'ordering': ['quantity_name'],
            },
        ),
    ]
