# Generated by Django 2.2.5 on 2019-09-27 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0003_auto_20190926_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField(verbose_name='Stock Open Date')),
                ('open_p', models.IntegerField(verbose_name='Stock Open P')),
                ('open_q', models.IntegerField(verbose_name='Stock Open Q')),
                ('open_n', models.IntegerField(verbose_name='Stock Open N')),
                ('open_d', models.IntegerField(verbose_name='Stock Open D')),
                ('open_l', models.IntegerField(verbose_name='Stock Open L')),
                ('open_xg', models.IntegerField(verbose_name='Stock Open XG')),
                ('open_y', models.IntegerField(verbose_name='Stock Open Y')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.Brand')),
                ('open_shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.Shop', verbose_name='Stock Open Shop')),
            ],
            options={
                'verbose_name': 'StockOpen',
                'verbose_name_plural': 'StockOpens',
                'ordering': ['open_date'],
            },
        ),
    ]
