# Generated by Django 2.2.5 on 2019-09-24 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0003_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bms.Category'),
            preserve_default=False,
        ),
    ]
