# Generated by Django 2.2.5 on 2019-09-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0005_stockclose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmsuser',
            name='user_role',
            field=models.CharField(max_length=5, verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='stockclose',
            name='close_qty_d',
            field=models.IntegerField(verbose_name='Stock Close Qty D'),
        ),
        migrations.AlterField(
            model_name='stockclose',
            name='close_qty_l',
            field=models.IntegerField(verbose_name='Stock Close Qty L'),
        ),
        migrations.AlterField(
            model_name='stockclose',
            name='close_qty_n',
            field=models.IntegerField(verbose_name='Stock Close Qty N'),
        ),
        migrations.AlterField(
            model_name='stockclose',
            name='close_qty_p',
            field=models.IntegerField(verbose_name='Stock Close Qty P'),
        ),
        migrations.AlterField(
            model_name='stockclose',
            name='close_qty_q',
            field=models.IntegerField(verbose_name='Stock Close Qty Q'),
        ),
        migrations.AlterField(
            model_name='stockclose',
            name='close_qty_xg',
            field=models.IntegerField(verbose_name='Stock Close Qty XG'),
        ),
        migrations.AlterField(
            model_name='stockclose',
            name='close_qty_y',
            field=models.IntegerField(verbose_name='Stock Close Qty Y'),
        ),
        migrations.AlterField(
            model_name='stockclose',
            name='close_sale_d',
            field=models.IntegerField(verbose_name='Stock Close Sale D'),
        ),
        migrations.AlterField(
            model_name='stockclose',
            name='close_sale_l',
            field=models.IntegerField(verbose_name='Stock Close Sale L'),
        ),
        migrations.AlterField(
            model_name='stockclose',
            name='close_sale_n',
            field=models.IntegerField(verbose_name='Stock Close Sale N'),
        ),
        migrations.AlterField(
            model_name='stockclose',
            name='close_sale_p',
            field=models.IntegerField(verbose_name='Stock Close Sale P'),
        ),
        migrations.AlterField(
            model_name='stockclose',
            name='close_sale_q',
            field=models.IntegerField(verbose_name='Stock Close Sale Q'),
        ),
        migrations.AlterField(
            model_name='stockclose',
            name='close_sale_xg',
            field=models.IntegerField(verbose_name='Stock Close Sale XG'),
        ),
        migrations.AlterField(
            model_name='stockclose',
            name='close_sale_y',
            field=models.IntegerField(verbose_name='Stock Close Sale Y'),
        ),
    ]
