# Generated by Django 2.2.5 on 2019-10-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0007_auto_20190927_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default='2019-10-01', verbose_name='Invoice Date'),
            preserve_default=False,
        ),
    ]
