# Generated by Django 2.2.5 on 2019-10-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0008_invoice_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_no_of_bottles',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_no_of_cases',
            field=models.IntegerField(default=30, verbose_name='Number of Cases'),
            preserve_default=False,
        ),
    ]
